name: Sync to Fork

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the original repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FORK_SYNC_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push main to fork
        run: |
          git push https://coo1river:${{ secrets.FORK_SYNC_TOKEN }}@github.com/coo1river/gameet-FE.git main --force
